spring:
  application:
    name: meetingroom

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  thymeleaf:
    cache: false  # 개발 중엔 false로 해서 새로고침만으로 화면 반영
  sql:
    init:
      mode: always
      #mode: never

server:
  port: 8080
  servlet:
    session:
      timeout: 30m  # 쿠키세션 30분 설정 추가

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.project.meetingroom.domain
